sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_d3af8d653fbb_key -iv $encrypted_d3af8d653fbb_iv -in gke.json.enc -out gke.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gke.json
